/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eindex.client;

import java.awt.Color;
import java.awt.Dimension;
import java.io.PrintWriter;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jovan
 */
public class MenuScreen extends javax.swing.JFrame {

    final private StartupScreen parent;
    final private PrintWriter pw;
    final private JPanel panel;
    
    final private static Dimension PANEL_DIMENSION = new Dimension(250, 300);
    
    private void overridableCalls() {
        panel.setSize(PANEL_DIMENSION);
        panel.setLocation(5, this.getY() + this.getHeight() - PANEL_DIMENSION.height - 45);
        panel.setBorder(BorderFactory.createLineBorder(Color.black));

        this.add(panel);

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    /**
     * Creates new form ExchangeMenu
     * @param parent
     * @param otherUsername
     */
    public MenuScreen(StartupScreen parent, String otherUsername) {
        super("E-Index Meni");
        initComponents();
        
        panel = new JPanel();

        this.parent = parent;
        this.pw = parent.getPw();

        this.overridableCalls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSendRequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSendRequest.setText("Posalji zahtev");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSendRequest)
                .addContainerGap(591, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSendRequest)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        
    }//GEN-LAST:event_btnSendRequestActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequest;
    // End of variables declaration//GEN-END:variables

}
